stages:
  - setup
  - build
  - deploy

variables:
  TERMINAL_PRELUDE: "[Robert Addon BOT]:"
  WORKINGDIRECTORY: ${CI_PROJECT_DIR}
  GIT_DEPTH: "0"

build-image:
  stage: build
  image: docker:latest
  before_script:
    - apk add --no-cache git
  script:
    - |
      cd "${WORKINGDIRECTORY}"

      echo -e "${TERMINAL_PRELUDE} Building latest"

      git clone https://git.rjns.dev/robert/bot-translations.git translations
      docker build -t "${CI_REGISTRY}/robert/addon-bot:latest" --pull .

deploy-image:
  stage: deploy
  image: docker:latest
  script:
    - |
      cd "${WORKINGDIRECTORY}"

      echo "${TERMINAL_PRELUDE} Logging into Registry..."
      echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin ${CI_REGISTRY}
      echo "${TERMINAL_PRELUDE} Logged in!"

      echo -e "${TERMINAL_PRELUDE} Pushing latest"
      docker push "${CI_REGISTRY}/robert/addon-bot:latest"

      echo -e "${TERMINAL_PRELUDE} Deploying..."